[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.18'

[fmt]
line_length = 120
int_types = 'long'
number_underscore = 'thousands'
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config